"""empty message

Revision ID: 3d7b4953b1ee
Revises: dbdabde037cc
Create Date: 2024-05-23 22:32:30.579174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d7b4953b1ee'
down_revision = 'dbdabde037cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_platforms', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_nullable=False,
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_platforms', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_nullable=True,
               nullable=False)
    # ### end Alembic commands ###
