"""empty message

Revision ID: 7026f9b26d3f
Revises: 191f8d1ddc48
Create Date: 2024-05-22 13:14:10.179568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7026f9b26d3f'
down_revision = '191f8d1ddc48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('street_address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('province', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_managers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('primary_address_id', sa.Integer(), nullable=False),
    sa.Column('secondary_address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['primary_address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['secondary_address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rental_properties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_manager_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('parcel_identifier', sa.String(), nullable=True),
    sa.Column('local_business_licence', sa.String(), nullable=True),
    sa.Column('property_type', sa.String(), nullable=False),
    sa.Column('ownership_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['property_manager_id'], ['property_managers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rental_property_id', sa.Integer(), nullable=False),
    sa.Column('submission_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['rental_property_id'], ['rental_properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rental_platforms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['rental_properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rental_platforms')
    op.drop_table('registrations')
    op.drop_table('rental_properties')
    op.drop_table('property_managers')
    op.drop_table('addresses')
    # ### end Alembic commands ###
