"""empty message

Revision ID: 894fe4847de6
Revises: 3d7b4953b1ee
Create Date: 2024-05-24 09:34:10.209903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894fe4847de6'
down_revision = '3d7b4953b1ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
       batch_op.add_column(sa.Column('sbc_account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('sbc_account_id')
    # ### end Alembic commands ###
