"""empty message

Revision ID: 4298c4cb3f07
Revises: 894fe4847de6
Create Date: 2024-05-30 14:55:23.502232

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4298c4cb3f07'
down_revision = '894fe4847de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('firstname', sa.VARCHAR(), nullable=False),
                    sa.Column('lastname', sa.VARCHAR(), nullable=False),
                    sa.Column('middlename', sa.VARCHAR(), nullable=True),
                    sa.Column('preferredname', sa.VARCHAR(), nullable=True),
                    sa.Column('email', sa.VARCHAR(), nullable=True),
                    sa.Column('address_id', sa.INTEGER(), nullable=False),
                    sa.Column('phone_number', sa.VARCHAR(), nullable=True),
                    sa.Column('phone_extension', sa.VARCHAR(), nullable=True),
                    sa.Column('fax_number', sa.VARCHAR(), nullable=True),
                    sa.Column('date_of_birth', sa.DATE(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['address_id'], ['addresses.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('eligibilities',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('registration_id', sa.INTEGER(), nullable=False),
                    sa.Column('is_principal_residence', sa.BOOLEAN(),
                              nullable=False, default=False),
                    sa.Column('agreed_to_rental_act', sa.BOOLEAN(),
                              nullable=False, default=False),
                    sa.Column('non_principal_option',
                              sa.VARCHAR(), nullable=True),
                    sa.Column('specified_service_provider',
                              sa.VARCHAR(), nullable=True),
                    sa.Column('agreed_to_submit', sa.BOOLEAN(),
                              nullable=False, default=False),
                    sa.ForeignKeyConstraint(['registration_id'], [
                                            'registrations.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('documents',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('eligibility_id', sa.INTEGER(), nullable=False),
                    sa.Column('file_name', sa.VARCHAR(), nullable=False),
                    sa.Column('file_type', sa.VARCHAR(), nullable=False),
                    sa.Column('path', sa.VARCHAR(), nullable=False),
                    sa.ForeignKeyConstraint(['eligibility_id'], [
                        'eligibilities.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(
            'registrations_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('property_managers', schema=None) as batch_op:
        batch_op.drop_column('user_id')
        batch_op.drop_column('primary_address_id')
        batch_op.drop_column('secondary_contact_user_id')
        batch_op.drop_column('secondary_address_id')

        batch_op.add_column(sa.Column('primary_contact_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('secondary_contact_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('property_managers_primary_contact_id_fkey', 'contacts', [
                                    'primary_contact_id'], ['id'])
        batch_op.create_foreign_key('property_managers_secondary_contact_id_fkey', 'contacts', [
                                    'secondary_contact_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferredname')
        batch_op.drop_column('phone_extension')
        batch_op.drop_column('fax_number')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_table('eligibilities')
    op.drop_table('contacts')

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    with op.batch_alter_table('property_managers', schema=None) as batch_op:
        batch_op.drop_column('primary_contact_id')
        batch_op.drop_column('secondary_contact_id')
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('primary_address_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('secondary_contact_user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('secondary_address_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('property_managers_primary_address_id_fkey', 'addresses', [
                                    'primary_address_id'], ['id'])
        batch_op.create_foreign_key('property_managers_secondary_address_id_fkey', 'addresses', [
                                    'secondary_address_id'], ['id'])
        batch_op.create_foreign_key('property_managers_secondary_contact_user_id_fkey', 'users', [
                                    'secondary_contact_user_id'], ['id'])
        batch_op.create_foreign_key(
            'property_managers_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferredname', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone_extension', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fax_number', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
