"""empty message

Revision ID: dbdabde037cc
Revises: 7026f9b26d3f
Create Date: 2024-05-22 23:25:46.897711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbdabde037cc'
down_revision = '7026f9b26d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferredname', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone_extension', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fax_number', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))

    with op.batch_alter_table('property_managers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secondary_contact_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('property_managers_secondary_contact_user_id_fkey', 'users', ['secondary_contact_user_id'], ['id'])

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street_address_additional', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_column('street_address_additional')

    with op.batch_alter_table('property_managers', schema=None) as batch_op:
        batch_op.drop_constraint('property_managers_secondary_contact_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('secondary_contact_user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('fax_number')
        batch_op.drop_column('phone_extension')
        batch_op.drop_column('preferredname')

    # ### end Alembic commands ###
